### PR TITLE
Update Metals and add its configuration

### PR DESCRIPTION
**Pull request by laughedelic**
- [x] Renamed `Scalameta` to `Metals` 🤘 
- [x] Updated default version 🚀 
- [x] Added configuration 🐙

### CODE REVIEW

**Comment by laughedelic** [comment]
Here's how it looks ✨ 

screen shot 2018-02-10 at 05 44 19

**Comment by laughedelic** [comment]
Depends on https://github.com/scalameta/metals/pull/196. I want to wait for it to change server artifact name.

**Comment by laughedelic** [comment]
/depends on https://github.com/scalameta/metals/pull/196. I want to wait for it to change server artifact name.

**Comment by cquiroz** [comment]
Wow, this is looking great!

**Comment by laughedelic** [comment]
This is ready and generally usable, so I'm going to merge it. But some settings don't actually work (i.e. server doesn't read them): https://github.com/scalameta/metals/issues/161. Some other settings that are not supported in Atom at the moment I just disabled, so when they get supported, it will be easy to bring them back.

**Pull request merged**
